version: "3.9"

services:
  # department postgres db
  postgres-serverConfig-service:
    container_name: microservices-serverConfig
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./data/db-serverConfig:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=server_config_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

  # department postgres db
  postgres-department-service:
    container_name: microservices-department
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - ./data/db-department:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database-microservices-department
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

  postgres-user-service:
    container_name: microservices-user
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5435:5432"
    volumes:
      - ./data/db-user:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database-microservices-user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

  postgres-customer-service:
    container_name: microservices-customer
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5436:5432"
    volumes:
      - ./data/db-customer:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database-microservices-customer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456